{
 "title": "Cert-manager-Kubernetes",
 "description": "The dashboard gives an overview of the SSL certs managed by cert-manager in Kubernetes",
 "tags": [
  "k8s",
  "cert-manager"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(certwatcher_read_certificate_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Valid Certificates",
   "type": "stat",
   "description": "The number if available certificates",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"True\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{namespace=~\"$namespace\"}) by (condition,name)>0",
     "legendFormat": "{{name}}:{{condition}}"
    }
   ]
  },
  {
   "title": "Overall requests per 2m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{namespace=~\"$namespace\"}[2m])) BY (status, path)>0",
     "legendFormat": "{{status}}:{{path}}"
    }
   ]
  },
  {
   "title": "Expiring Certificates",
   "type": "stat",
   "description": "The number of certificates that will expire within the next 14 days",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\"} < (time()+(14*24*3600)))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Total ACME Requests",
   "type": "stat",
   "description": "Total number of HTTP requests",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gültigkeitsdauer des Zertifikats",
   "type": "table",
   "description": "Time before the certificates expire",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sort(certmanager_certificate_renewal_timestamp_seconds{namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ablaufdatum",
   "type": "timeseries",
   "description": "Time before the certificates expire",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}