{
 "title": "Contour Global Metrics",
 "description": "A Dashboard that monitors general statistics for Contour Ingress Controller (Projectcontour)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(contour_build_info,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": "vulcavo-system-contour-ingress-envoy-metrics"
   }
  ]
 },
 "panels": [
  { "title": "Contour Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Namespace" },
  {
   "title": "Avg Memory Physical Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(envoy_server_memory_physical_size{namespace=~\"$namespace\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Live servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{namespace=~\"$namespace\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(envoy_server_uptime{namespace=~\"$namespace\",service=~\"$service\"}))"
    }
   ]
  },
  {
   "title": "HTTPProxy Resource Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(contour_httpproxy)", "legendFormat": "Total HTTPProxy" },
    { "expr": "sum(contour_httpproxy_valid)", "legendFormat": "Valid HTTPProxy" },
    { "expr": "sum(contour_httpproxy_invalid)", "legendFormat": "Invalid HTTPProxy" }
   ]
  },
  {
   "title": "Reload Runtime Update Success ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Reloads" } },
   "targets": [
    {
     "expr": "sum(increase(envoy_runtime_update_attempt{namespace=~\"$namespace\",service=~\"$service\"}[1m]))",
     "legendFormat": "Config Attempt"
    },
    {
     "expr": "sum(increase(envoy_runtime_update_failure{namespace=~\"$namespace\",service=~\"$service\"}[1m])) + sum(increase(envoy_runtime_update_rejected{namespace=~\"$namespace\",service=~\"$service\"}[1m]))",
     "legendFormat": "Config Failed/Rejected"
    },
    {
     "expr": "sum(increase(envoy_runtime_update_success{namespace=~\"$namespace\",service=~\"$service\"}[1m]))",
     "legendFormat": "Config Success"
    }
   ]
  },
  {
   "title": "Node State per Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_state{namespace=~\"$namespace\",service=~\"$service\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Invalid HTTPProxy",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(contour_httpproxy_invalid{namespace=~\"$namespace\"}) by (exported_namespace,vhost)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\",service=~\"$service\"}[${__range_s}s])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Reqs (5m)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last five minute window",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\",service=~\"$service\"}[5m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Conns (period)",
   "type": "stat",
   "description": "This is the total number of connections made in this period (top-right period selected)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\",service=~\"$service\"}[${__range_s}s])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Conns (5m)",
   "type": "stat",
   "description": "This is the number of new connections made to the ingress in the five minutes.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\",service=~\"$service\"}[5m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream RPS",
   "type": "timeseries",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (service,namespace)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{namespace=~\"$namespace\",service=~\"$service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "timeseries",
   "description": "Displays the number of Connections per Second being performed against each Upstream.",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\",service=~\"$service\"}[1m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{namespace=~\"$namespace\",service=~\"$service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Cluster Drilldown",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(label_replace(label_replace(label_replace(rate(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\",service=~\"$service\"}[1m]), \"ingress_namespace\", \"$1\", \"envoy_cluster_name\", \"^([a-z\\\\-]+)_.*\"), \"ingress_service\", \"$1\", \"envoy_cluster_name\", \"^[a-z\\\\-]+_([a-z\\\\-]+)_\\\\d+$\"), \"ingress_port\", \"$1\", \"envoy_cluster_name\", \".*_(\\\\d+)$\")) by (ingress_service, ingress_namespace)"
    },
    {
     "expr": "sum(label_replace(label_replace(label_replace(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\",service=~\"$service\"}[1m]), \"ingress_namespace\", \"$1\", \"envoy_cluster_name\", \"^([a-z\\\\-]+)_.*\"), \"ingress_service\", \"$1\", \"envoy_cluster_name\", \"^[a-z\\\\-]+_([a-z\\\\-]+)_\\\\d+$\"), \"ingress_port\", \"$1\", \"envoy_cluster_name\", \".*_(\\\\d+)$\")) by (ingress_service, ingress_namespace)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(label_replace(label_replace(label_replace(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\",service=~\"$service\"}[1m]), \"ingress_namespace\", \"$1\", \"envoy_cluster_name\", \"^([a-z\\\\-]+)_.*\"), \"ingress_service\", \"$1\", \"envoy_cluster_name\", \"^[a-z\\\\-]+_([a-z\\\\-]+)_\\\\d+$\"), \"ingress_port\", \"$1\", \"envoy_cluster_name\", \".*_(\\\\d+)$\")) by (le, ingress_namespace, ingress_service))"
    },
    {
     "expr": "histogram_quantile(0.90, sum(label_replace(label_replace(label_replace(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\",service=~\"$service\"}[1m]), \"ingress_namespace\", \"$1\", \"envoy_cluster_name\", \"^([a-z\\\\-]+)_.*\"), \"ingress_service\", \"$1\", \"envoy_cluster_name\", \"^[a-z\\\\-]+_([a-z\\\\-]+)_\\\\d+$\"), \"ingress_port\", \"$1\", \"envoy_cluster_name\", \".*_(\\\\d+)$\")) by (le, ingress_namespace, ingress_service))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(label_replace(label_replace(label_replace(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\",service=~\"$service\"}[1m]), \"ingress_namespace\", \"$1\", \"envoy_cluster_name\", \"^([a-z\\\\-]+)_.*\"), \"ingress_service\", \"$1\", \"envoy_cluster_name\", \"^[a-z\\\\-]+_([a-z\\\\-]+)_\\\\d+$\"), \"ingress_port\", \"$1\", \"envoy_cluster_name\", \".*_(\\\\d+)$\")) by (le, ingress_namespace, ingress_service))"
    }
   ]
  },
  {
   "title": "Upstream Responses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$namespace\",service=~\"$service\", envoy_response_code_class=~\"1\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}} - 1xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$namespace\",service=~\"$service\", envoy_response_code_class=~\"2\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}  - 2xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$namespace\",service=~\"$service\", envoy_response_code_class=~\"3\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}  - 3xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$namespace\",service=~\"$service\", envoy_response_code_class=~\"4\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}} - 4xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$namespace\",service=~\"$service\", envoy_response_code_class=~\"5\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}} - 5xx"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{service=~\"$service\",namespace=~\"$namespace\"}[1m])) by (service, namespace)",
     "legendFormat": "{{namespace}}/{{service}} - In"
    },
    {
     "expr": "-sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{service=~\"$service\",namespace=~\"$namespace\"}[1m])) by (service, namespace)",
     "legendFormat": "{{namespace}}/{{service}} - Out"
    }
   ]
  },
  { "title": "DownStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_total{namespace=~\"$namespace\",service=~\"$service\"}[${__range_s}s])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Reqs (5m)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last five minute window",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_total{namespace=~\"$namespace\",service=~\"$service\"}[5m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Conns (period)",
   "type": "stat",
   "description": "This is the total number of connections made in this period (top-right period selected)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{namespace=~\"$namespace\",service=~\"$service\"}[${__range_s}s])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Conns (5m)",
   "type": "stat",
   "description": "This is the number of new connections made to the ingress in the five minutes.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{namespace=~\"$namespace\",service=~\"$service\"}[5m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Downstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{service=~\"$service\",namespace=~\"$namespace\"}[1m])) by (service, namespace)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_rq_active{namespace=~\"$namespace\",service=~\"$service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{service=~\"$service\",namespace=~\"$namespace\"}[1m])) by (service, namespace)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{service=~\"$service\",namespace=~\"$namespace\"}) by (service, namespace)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_https\", service=~\"$service\",namespace=~\"$namespace\"}[1m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}} - In"
    },
    {
     "expr": "-sum(irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_https\", service=~\"$service\",namespace=~\"$namespace\"}[1m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}} - Out"
    }
   ]
  }
 ]
}