{
 "title": "Query Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Queries >10s in 5m range at Envoy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max_over_time(\n  {namespace=\"vulcavo-system\", pod=~\"vulcavo-system-contour-ingress-envoy.*\"}\n  | pattern \"[<ts>] \\\"<method> <path> <proto>\\\" <status> <flags> <bytes_in> <bytes_out> <duration_ms> <upstream_ms> \\\"<client_ip>\\\" \\\"<ua>\\\" \\\"<request_id>\\\" \\\"<host>\\\" \\\"<upstream_host>\\\"\"\n  | unwrap duration_ms\n  [5m]\n) by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Querytimes by Upstream host",
   "type": "timeseries",
   "description": "Upstream by IP, check with kubctl -n internal get pods -o wide to find the right pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max_over_time(\n  {namespace=\"vulcavo-system\", pod=~\"vulcavo-system-contour-ingress-envoy.*\"}\n  |= \"vulcavo.organizer.internal.vulcavo.dev\"\n  | pattern \"[<ts>] \\\"<method> <path> <proto>\\\" <status> <flags> <bytes_in> <bytes_out> <duration_ms> <upstream_ms> \\\"<client_ip>\\\" \\\"<ua>\\\" \\\"<request_id>\\\" \\\"<host>\\\" \\\"<upstream_host>\\\"\"\n  | unwrap duration_ms\n  [5m]\n) by (upstream_host)",
     "legendFormat": "{{upstream_host}}"
    }
   ]
  },
  {
   "title": "Queries >10s",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"vulcavo-system\", pod=~\"vulcavo-system-contour-ingress-envoy.*\"}\n| pattern \"[<ts>] \\\"<method> <path> <proto>\\\" <status> <flags> <bytes_in> <bytes_out> <duration_ms> <upstream_ms> \\\"<client_ip>\\\" \\\"<ua>\\\" \\\"<request_id>\\\" \\\"<host>\\\" \\\"<upstream_host>\\\"\"\n| duration_ms >= 10000"
    }
   ]
  }
 ]
}