{
 "title": "Redis Server Overview",
 "description": "A Redis Server Performance Monitoring Redis Server with Prometheus and telegraf agent using Redis agent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Server",
    "label": "Server",
    "query": {
     "query": "label_values(redis_uptime,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Genral Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Clusters",
   "type": "stat",
   "description": "Total Clusters Enabled",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cluster_enabled{host=\"$Server\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "cluster_enabled" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Redis Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime{host=\"$Server\"}"
    }
   ]
  },
  {
   "title": "Total Clients Connected",
   "type": "stat",
   "description": "Total Clients Connected",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_clients{host=\"$Server\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Redis User CPU",
   "type": "timeseries",
   "description": "User CPU consumed by the Redis server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Uuser CPU",
     "expr": "sum by (instance)(irate(redis_used_cpu_user{host=~\"$Server\"}[10m])) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "Redis User CPU",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "used_cpu_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Connection Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(redis_total_connections_received{host=\"$Server\"}[$__interval])",
     "legendFormat": "$Server"
    }
   ]
  },
  {
   "title": "Redis Memory Utilization",
   "type": "timeseries",
   "description": "Total number of bytes allocated by Redis using its allocator",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total Used Memory",
     "expr": "redis_used_memory{host=~\"$Server\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "mem_used",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    },
    {
     "expr": "redis_used_memory_lua{server=~\"$Server\"}",
     "legendFormat": "mem_lua"
    },
    {
     "expr": "redis_used_memory_peak{server=\"$Server\"}",
     "legendFormat": "mem_peak"
    },
    {
     "expr": "redis_used_memory_rss{server=\"$Server\"}",
     "legendFormat": "mem_rss"
    }
   ]
  },
  { "title": "RedisperCacheStats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Hit / Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "redis_keyspace_hitrate{host=\"$Server\"} * 100",
     "legendFormat": "redis_hitrate"
    }
   ]
  },
  {
   "title": "Total Tracking Items",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_tracking_total_items{host=\"$Server\"}",
     "legendFormat": "total_tracking_items"
    }
   ]
  },
  {
   "title": "Evicted / Expired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_evicted_keys{host=\"$Server\"}",
     "legendFormat": "evicted_keys"
    },
    {
     "expr": "redis_expired_keys{server=\"$Server\"}",
     "legendFormat": "expirted_keys"
    }
   ]
  },
  {
   "title": "Total Keyspaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_tracking_total_keys{host=\"$Server\"}"
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "timeseries",
   "description": "Total number of commands processed by the server",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Total Commands Processed",
     "expr": "sum by (instance)(irate(redis_total_commands_processed{host=~\"$Server\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "processed_commands",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_commands_processed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "stat",
   "description": "Total Commands Processed",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_total_commands_processed{host=\"$Server\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_commands_processed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked / Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_blocked_clients{host=\"$Server\"}",
     "legendFormat": "blocked_clients"
    },
    {
     "expr": "redis_tracking_clients{server=\"$Server\"}",
     "legendFormat": "connected_clients"
    }
   ]
  },
  {
   "title": "Instantaneous OPS per sec",
   "type": "timeseries",
   "description": "Number of commands processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Instantaneous OPS per sec",
     "expr": "redis_instantaneous_ops_per_sec{host=\"$Server\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "$Server",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "instantaneous_ops_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  { "title": "RedisperformanceStats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Received / Rejected Connections",
   "type": "timeseries",
   "description": "Total number of connections accepted by the server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Total Connections Received",
     "expr": "sum by (server)(irate(redis_total_connections_received{host=~\"$Server\"}[10m])) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "received",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_connections_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    },
    {
     "expr": "sum by (server)(irate(redis_rejected_connections{server=~\"$Server\"}[10m])) * 100",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Network Input / Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_total_net_input_bytes{host=\"$Server\"}[$__interval])",
     "legendFormat": "input_bytes"
    },
    {
     "expr": "rate(redis_total_net_output_bytes{host=\"$Server\"}[$__interval])",
     "legendFormat": "output_bytes"
    }
   ]
  }
 ]
}