{
 "title": "Upcloud LB",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "upcloud_load_balancer_frontend_request_rate",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "upcloud_load_balancer_frontend_current_sessions",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(upcloud_load_balancer_frontend_total_http_responses_1xx{frontend=~\"http|https\"}[5m])\n+\n  increase(upcloud_load_balancer_frontend_total_http_responses_2xx{frontend=~\"http|https\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(upcloud_load_balancer_frontend_total_http_responses_5xx{frontend=~\"http|https\"}[5m]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "HTTP 3xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(upcloud_load_balancer_frontend_total_http_responses_3xx{frontend=~\"http|https\"}[5m]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(upcloud_load_balancer_frontend_total_http_responses_4xx{frontend=~\"http|https\"}[5m]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Frontend Total Request Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upcloud_load_balancer_frontend_total_request_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Total Response Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upcloud_load_balancer_frontend_total_response_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "AVG Backend Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "upcloud_load_balancer_backend_avg_server_response_time_ms",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "upcloud_load_balancer_backend_current_sessions",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(upcloud_load_balancer_backend_total_http_responses_1xx[5m])\n+\n  increase(upcloud_load_balancer_backend_total_http_responses_2xx[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(upcloud_load_balancer_backend_total_http_responses_5xx[5m]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "HTTP 3xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(upcloud_load_balancer_backend_total_http_responses_3xx[5m]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(upcloud_load_balancer_backend_total_http_responses_4xx[5m]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Backend Total Request Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upcloud_load_balancer_backend_total_request_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Total Response Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upcloud_load_balancer_backend_total_response_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(upcloud_load_balancer_backend_connections_waiting)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Reachable Members",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (backend) (\n  upcloud_load_balancer_member_status{status=\"up\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Response Time by Member",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (member) (upcloud_load_balancer_member_avg_server_response_time_ms\nand on (load_balancer_uuid, backend, member)\nupcloud_load_balancer_member_status{status=\"up\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (member) (\n  (\n    increase(upcloud_load_balancer_member_total_http_responses_1xx[5m])\n  +\n    increase(upcloud_load_balancer_member_total_http_responses_2xx[5m])\n  )\n  and on (load_balancer_uuid, backend, member)\n  upcloud_load_balancer_member_status{status=\"up\"} == 1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (member) (\n  (\n    increase(upcloud_load_balancer_member_total_http_responses_5xx[5m])\n  )\n  and on (load_balancer_uuid, backend, member)\n  upcloud_load_balancer_member_status{status=\"up\"} == 1\n)",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "HTTP 3xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (member) (\n  (\n    increase(upcloud_load_balancer_member_total_http_responses_3xx[5m])\n  )\n  and on (load_balancer_uuid, backend, member)\n  upcloud_load_balancer_member_status{status=\"up\"} == 1\n)",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (member) (\n  (\n    increase(upcloud_load_balancer_member_total_http_responses_4xx[5m])\n  )\n  and on (load_balancer_uuid, backend, member)\n  upcloud_load_balancer_member_status{status=\"up\"} == 1\n)",
     "legendFormat": "{{frontend}}"
    }
   ]
  }
 ]
}